### ISSUE TITLE
ob_start() and var_dump() array "Couldn't fetch mysqli_result"

### ISSUE THREAD

**Issue by jackbentley** [krakjoe/uopz#112]
**Problem:**
When enabling output buffering, and `var_dump()`ing a large array, uopz causes the error `Couldn't fetch mysqli_result`.

I believe it also causes the iteration over the array to fail after so many iterations - however, I can't confirm this.

It may be something to do with recursion?

This is not present when uopz is not enabled. The problem also goes away when xdebug is enabled.

**Log example:**
```
[14-May-2019 12:56:15 Europe/London] PHP Warning:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: var_dump(): Couldn't fetch mysqli_result in /var/www/html/vendor/klein/klein/src/Klein/Klein.php:446
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleError(2, 'var_dump(): Cou...', '/var/www/html/v...', 446, Array)
#1 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(446): var_dump(Object(Klein\DataCollection\RouteCollection))
#2 /var/www/html/vendor/myapp/myappframework/src/Router/Driver/Klein.php(110): Klein\Klein->dispatch(Object(Klein\Request), NULL, true, 1)
#3 /var/www/html/vendor/myapp/myappframework/src/Router/Router.php(96): MyappFramework\Router\Driver\Klein->dispatch(Object(MyappFramework\Router\Driver\Klein\Request))
#4 /var/www/html/src/Myapp/Bundle/CCRouteBundle/Controller/MyappRouteController.php(32): MyappFramework\Router\Router->dispatch()
#5 [internal function]: Myapp\Bundle\CCRouteBundle\Controller\MyappRouteController->__invoke()
#6 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/H in /var/www/html/vendor/klein/klein/src/Klein/Klein.php on line 446
[14-May-2019 12:56:15 Europe/London] PHP Fatal error:  Allowed memory size of 335544320 bytes exhausted (tried to allocate 266354688 bytes) in /var/www/html/vendor/klein/klein/src/Klein/Klein.php on line 446
[14-May-2019 12:56:15 Europe/London] PHP Fatal error:  Allowed memory size of 335544320 bytes exhausted (tried to allocate 266354688 bytes) in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Debug/ExceptionHandler.php on line 197
[14-May-2019 12:56:15 Europe/London] PHP Fatal error:  Allowed memory size of 335544320 bytes exhausted (tried to allocate 266338304 bytes) in Unknown on line 0
```

**Reproduce case:**
I haven't tried reproducing this outside of my app, however, we are using the Klein router, and the issue is happening within that library. It's failing to match routes because the matching/looping is occurring after starting output buffering.

https://github.com/klein/klein.php/blob/v2.1.2/src/Klein/Klein.php#L441-L445
 
```php
// Dumps fine here
var_dump($this->routes);

// Start output buffering
ob_start();
$this->output_buffer_level = ob_get_level();

// Errors here
var_dump($this->routes);
```

**System Info:**
```
# php -v
PHP 7.2.18 (cli) (built: Apr 30 2019 15:26:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.18, Copyright (c) 1999-2018, by Zend Technologies
```

```
# php -m
[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
intl
json
libxml
mbstring
mcrypt
memcache
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
uopz
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
yaml
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

```
# yum list installed | grep php
php.x86_64                          7.2.18-1.el7.remi                @remi-php72
php-PsrLog.noarch                   1.0.2-2.el7                      @epel      
php-bcmath.x86_64                   7.2.18-1.el7.remi                @remi-php72
php-cli.x86_64                      7.2.18-1.el7.remi                @remi-php72
php-common.x86_64                   7.2.18-1.el7.remi                @remi-php72
php-composer-ca-bundle.noarch       1.0.2-1.el7                      @epel      
php-composer-semver.noarch          1.4.2-1.el7                      @epel      
php-composer-spdx-licenses.noarch   1.4.0-1.el7                      @epel      
php-composer-xdebug-handler.noarch  1.3.0-1.el7                      @epel      
php-fedora-autoloader.noarch        1.0.0-1.el7                      @epel      
php-gd.x86_64                       7.2.18-1.el7.remi                @remi-php72
php-intl.x86_64                     7.2.18-1.el7.remi                @remi-php72
php-json.x86_64                     7.2.18-1.el7.remi                @remi-php72
php-jsonlint.noarch                 1.6.1-1.el7                      @epel      
php-justinrainbow-json-schema5.noarch
php-mbstring.x86_64                 7.2.18-1.el7.remi                @remi-php72
php-mysqlnd.x86_64                  7.2.18-1.el7.remi                @remi-php72
php-opcache.x86_64                  7.2.18-1.el7.remi                @remi-php72
php-paragonie-random-compat.noarch  2.0.12-1.el7                     @epel      
php-password-compat.noarch          1.0.4-1.el7                      @epel      
php-pdo.x86_64                      7.2.18-1.el7.remi                @remi-php72
php-pecl-apcu.x86_64                5.1.12-1.el7.remi.7.2            @remi-php72
php-pecl-igbinary.x86_64            2.0.7-1.el7.remi.7.2             @remi-php72
php-pecl-mcrypt.x86_64              1.0.1-6.el7.remi.7.2             @remi-php72
php-pecl-memcache.x86_64            3.0.9-0.9.20170802.e702b5f.el7.remi.7.2
                                                                     @remi-php72
php-pecl-memcached.x86_64           3.0.4-2.el7.remi.7.2             @remi-php72
php-pecl-msgpack.x86_64             2.0.2-4.el7.remi.7.2             @remi-php72
php-pecl-uopz.x86_64                6.0.1-2.el7.remi.7.2             @remi-php72
php-pecl-xdebug.x86_64              2.6.1-1.el7.remi.7.2             @remi-php72
php-pecl-yaml.x86_64                2.0.2-1.el7.remi.7.2             @remi-php72
php-pecl-zip.x86_64                 1.15.3-1.el7.remi.7.2            @remi-php72
php-process.x86_64                  7.2.18-1.el7.remi                @remi-php72
php-seld-phar-utils.noarch          1.0.1-1.el7                      @epel      
php-soap.x86_64                     7.2.18-1.el7.remi                @remi-php72
php-symfony-browser-kit.noarch      2.8.12-2.el7                     @epel      
php-symfony-class-loader.noarch     2.8.12-2.el7                     @epel      
php-symfony-common.noarch           2.8.12-2.el7                     @epel      
php-symfony-config.noarch           2.8.12-2.el7                     @epel      
php-symfony-console.noarch          2.8.12-2.el7                     @epel      
php-symfony-css-selector.noarch     2.8.12-2.el7                     @epel      
php-symfony-debug.noarch            2.8.12-2.el7                     @epel      
php-symfony-dependency-injection.noarch
php-symfony-dom-crawler.noarch      2.8.12-2.el7                     @epel      
php-symfony-event-dispatcher.noarch 2.8.12-2.el7                     @epel      
php-symfony-expression-language.noarch
php-symfony-filesystem.noarch       2.8.12-2.el7                     @epel      
php-symfony-finder.noarch           2.8.12-2.el7                     @epel      
php-symfony-http-foundation.noarch  2.8.12-2.el7                     @epel      
php-symfony-http-kernel.noarch      2.8.12-2.el7                     @epel      
php-symfony-polyfill.noarch         1.5.0-1.el7                      @epel      
php-symfony-process.noarch          2.8.12-2.el7                     @epel      
php-symfony-var-dumper.noarch       2.8.12-2.el7                     @epel      
php-symfony-yaml.noarch             2.8.12-2.el7                     @epel      
php-xml.x86_64                      7.2.18-1.el7.remi                @remi-php72
php-xmlrpc.x86_64                   7.2.18-1.el7.remi                @remi-php72
```

```
# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
```

**Comment by krakjoe** [comment]
This looks like normal behaviour: uopz uses more memory when loaded, that's expected. Your configured limit would seem to be under the requirements of your application plus the overhead of uopz. I suggest you just try raising the memory limit.

If there is no limit that works, or there is otherwise indeed a bug, please do open another bug report.

**Comment by jackbentley** [comment]
I'm not convinced this is related to memory. The example provided is just a large array which dumps fine without the extension enabled.

I'm now receiving the same error on an application when trying to build it's Symfony cache. I profiled the page and it's using ~40M. PHP is configured with a 320M memory limit.
