### ISSUE TITLE
Segfault in test suite with 8.1.2

### ISSUE THREAD

**Issue by remicollet** [krakjoe/uopz#160]
```
========DIFF========
--
     bool(false)
     unset
     bool(true)
010+ 
011+ Termsig=11
010- bool(true)
011- string(%d) "Call to private method Foo::priv() from %s"
012- string(%d) "will not replace existing method %s::%s, use uopz_set_return instead"
013- string(%d) "will not replace existing function %s, use uopz_set_return instead"
014- string(%d) "__destruct"
015- string(%d) "__destruct"
========DONE========
FAIL uopz_add_function [tests/012.phpt] 

```

**Comment by cmb69** [comment]
The test passes for me on Windows. Is this a platform specific issue?

**Comment by remicollet** [comment]
Yes seems platform specific.

Only happens on Fedora 36, with GCC 12

**Comment by remicollet** [comment]
```
(gdb) bt
#0  0x0000555555817a54 in ZEND_BIND_STATIC_SPEC_CV_UNUSED_HANDLER () at /usr/src/debug/php-8.1.2-1.fc36.remi.x86_64/Zend/zend_vm_execute.h:48026
#1  0x000055555585752b in execute_ex (ex=0x2080546) at /usr/src/debug/php-8.1.2-1.fc36.remi.x86_64/Zend/zend_vm_execute.h:59360
#2  0x000055555585ef5d in zend_execute (op_array=0x7ffff7293000, return_value=0x0) at /usr/src/debug/php-8.1.2-1.fc36.remi.x86_64/Zend/zend_vm_execute.h:59673
#3  0x00005555557eebf0 in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /usr/src/debug/php-8.1.2-1.fc36.remi.x86_64/Zend/zend.c:1761
#4  0x000055555578977a in php_execute_script (primary_file=<optimized out>) at /usr/src/debug/php-8.1.2-1.fc36.remi.x86_64/main/main.c:2535
#5  0x00005555558d84cf in do_cli (argc=80, argv=0x555555e0feb0) at /usr/src/debug/php-8.1.2-1.fc36.remi.x86_64/sapi/cli/php_cli.c:965
#6  0x000055555563aac3 in main (argc=80, argv=0x555555e0feb0) at /usr/src/debug/php-8.1.2-1.fc36.remi.x86_64/sapi/cli/php_cli.c:1367

```

**Comment by remicollet** [comment]
Notice seems to also happen with older GCC on aarch64

**Comment by cmb69** [comment]
@remicollet, is this still unresolved, or maybe was it just an optimization glitch that had been fixed in the meantime?
