### ISSUE TITLE
Segmentation fault (uopz_set_return)

### ISSUE THREAD

**Issue by kna** [krakjoe/uopz#48]
When I ran following script with uopz( 715677760322ada7ae0b61672561de46844b2392 ), I faced Segmentation fault.

```
vagrant@vagrant:~$ cat test.php
<?php

function f1(){}
function f2(){}

uopz_set_return('f1','f2', 1);
uopz_unset_return('f1');
uopz_set_return('f1','f2', 1);

echo 'Done';

vagrant@vagrant:~$ php -d extension=uopz/modules/uopz.so test.php
Segmentation fault (core dumped)

vagrant@vagrant:~$ gdb php --core core
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 14819]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php -d extension=uopz/modules/uopz.so test.php'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055c81fbc4ba5 in instanceof_function ()
(gdb) bt
#0  0x000055c81fbc4ba5 in instanceof_function ()
#1  0x00007f16e8728882 in zif_uopz_set_return (execute_data=0x7f16ed8130c0, return_value=0x7f16ed813090) at /home/vagrant/uopz/uopz.c:151
#2  0x000055c81fbbdc9a in dtrace_execute_internal ()
#3  0x000055c81fc52940 in ?? ()
#4  0x000055c81fc0df8b in execute_ex ()
#5  0x000055c81fbbdb31 in dtrace_execute_ex ()
#6  0x000055c81fc61d57 in zend_execute ()
#7  0x000055c81fbcdd33 in zend_execute_scripts ()
#8  0x000055c81fb6e5a0 in php_execute_script ()
#9  0x000055c81fc63a17 in ?? ()
#10 0x000055c81fa530a4 in main ()

vagrant@vagrant:~$ php -v
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by kna** [comment]
@krakjoe 
Thank you.

I'll use a closure instead of a function name.
```
<?php
function f1(){}
function f2(){}

$f2c=(new ReflectionFunction('f2'))->getClosure();
uopz_set_return('f1',$f2c, 1);
uopz_unset_return('f1');
uopz_set_return('f1',$f2c, 1);
echo 'Done';
```
