### ISSUE TITLE
doubled execution in 5.0.2

### ISSUE THREAD

**Issue by jcshort** [krakjoe/uopz#75]
At first I thought this was specific to phar archives as described by @remicollet in #60, but it looks to be all CLI usage.  Examples pasted below are from the public wordpress:php7.2 docker image, with uopz installed via PECL and enabled in /usr/local/etc/php/conf.d/uopz.ini.  Opcache is disabled.

Here's a WP-CLI phar with uopz disabled:
```
root@9a582b1fb3d4:/usr/src/wordpress# php -d uopz.disable=1 ~/wp-cli.phar --allow-root db query
<snip>
MariaDB [nope]> Bye
```

and enabled, the extra output just happens to be errors but that's not strictly relevant:
```
root@9a582b1fb3d4:/usr/src/wordpress# php -d uopz.disable= ~/wp-cli.phar --allow-root db query
<snip>
MariaDB [nope]> Bye

Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down.
Fatal error: Uncaught Error: Call to undefined function wp_cache_get() in /usr/src/wordpress/wp-includes/functions.php:1364
Stack trace:
#0 phar:///root/wp-cli.phar/php/utils-wp.php(9): is_blog_installed()
#1 phar:///root/wp-cli.phar/php/WP_CLI/Runner.php(1293): WP_CLI\Utils\wp_not_installed()
#2 [internal function]: WP_CLI\Runner->WP_CLI\{closure}(Array)
#3 /usr/src/wordpress/wp-includes/class-wp-hook.php(286): call_user_func_array(Object(Closure), Array)
#4 /usr/src/wordpress/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#5 /usr/src/wordpress/wp-includes/functions.php(1125): apply_filters('nocache_headers', Array)
#6 /usr/src/wordpress/wp-includes/functions.php(1143): wp_get_nocache_headers()
#7 /usr/src/wordpress/wp-includes/functions.php(3767): nocache_headers()
#8 /usr/src/wordpress/wp-includes/load.php(422): dead_db()
#9 /usr/src/wordpress/wp-settings.php(110): wp_set_wpdb_vars()
#10 phar:///root/wp-cli.phar/php/WP_CLI/Runner.php(1174): require('/usr/src/wordpr...')
#11 phar:///root/wp-cli.phar/p in /usr/src/wordpress/wp-includes/functions.php on line 1364
```

we can also see this in wordpress without PHAR involved:
```
root@9a582b1fb3d4:/usr/src/wordpress# php -d uopz.disable=1 index.php
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Database Error</title>

</head>
<body>
	<h1>Error establishing a database connection</h1>
</body>
</html>
```

okay, we just want to print some html and exit:
```
root@9a582b1fb3d4:/usr/src/wordpress# php -d uopz.disable= index.php
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Database Error</title>

</head>
<body>
	<h1>Error establishing a database connection</h1>
</body>
</html>

Warning: Cannot modify header information - headers already sent by (output started at /usr/src/wordpress/wp-includes/functions.php:3770) in /usr/src/wordpress/wp-includes/pluggable.php on line 1216

Fatal error: Cannot redeclare wptexturize() (previously declared in /usr/src/wordpress/wp-includes/formatting.php:51) in /usr/src/wordpress/wp-includes/formatting.php on line 300
```

FWIW, a very plain test file does not run afoul of the issue:
```
root@9a582b1fb3d4:~# echo '<?php var_dump(ini_get("uopz.disable"));?>' > test.php
root@9a582b1fb3d4:~# php -d uopz.disable=1 test.php
string(1) "1"
root@9a582b1fb3d4:~# php -d uopz.disable= test.php
string(0) ""
```

is uopz hooking something by default that phar and/or wordpress would be stumbling into here?

**Comment by jcshort** [comment]
seems to be allow_exit from https://github.com/krakjoe/uopz/issues/65
